const problemsData = [
    {
        "id": "2839",
        "date": "Mar 29, 2026",
        "title": "2839. Check if Strings Can be Made Equal With Operations",
        "difficulty": "Easy",
        "tags": "String, Simulation",
        "description": "<p>You are given two strings <code>s1</code> and <code>s2</code>, both of length 4, consisting of lowercase English letters.</p>\n<br>\n<p>You can apply the following operation on any of the two strings any number of times: Choose any two indices <code>i</code> and <code>j</code> such that <code>j - i = 2</code>, then swap the two characters at those indices in the string. Return <code>true</code> if you can make the strings equal, and <code>false</code> otherwise.</p>",
        "approach": "Since the strings are only of length 4, and we can only swap characters at distance 2, we can simply generate all valid permutations for both strings independently by swapping indices (0,2) and (1,3). If any generated permutation of s1 matches any generated permutation of s2, they can be made equal.",
        "cpp": "class Solution {\npublic:\n    bool canBeEqual(string s1, string s2) {\n        for (const string& a : swappedStrings(s1))\n            for (const string& b : swappedStrings(s2))\n                if (a == b)\n                    return true;\n        return false;\n    }\n\nprivate:\n    vector<string> swappedStrings(const string& s) {\n        vector<char> chars(s.begin(), s.end());\n        return {s, \n                string({chars[2], chars[1], chars[0], chars[3]}),\n                string({chars[0], chars[3], chars[2], chars[1]}),\n                string({chars[2], chars[3], chars[0], chars[1]})};\n    }\n};",
        "java": "class Solution {\n    public boolean canBeEqual(String s1, String s2) {\n        for (String a : swappedStrings(s1)) {\n            for (String b : swappedStrings(s2)) {\n                if (a.equals(b)) return true;\n            }\n        }\n        return false;\n    }\n\n    private List<String> swappedStrings(String s) {\n        char[] c = s.toCharArray();\n        return Arrays.asList(s, \n            new String(new char[]{c[2], c[1], c[0], c[3]}),\n            new String(new char[]{c[0], c[3], c[2], c[1]}),\n            new String(new char[]{c[2], c[3], c[0], c[1]}));\n    }\n}",
        "python": "class Solution:\n    def canBeEqual(self, s1: str, s2: str) -> bool:\n        def get_swaps(s):\n            yield s\n            yield s[2] + s[1] + s[0] + s[3]\n            yield s[0] + s[3] + s[2] + s[1]\n            yield s[2] + s[3] + s[0] + s[1]\n\n        return any(a == b for a in get_swaps(s1) for b in get_swaps(s2))",
        "timeComplexity": "O(1) - Generating the swapped strings and comparing them takes O(1) time since the string length is fixed at 4.",
        "spaceComplexity": "O(1) - We only store exactly 4 permutations of size 4."
    },
    {
        "id": "2840",
        "title": "Check if Strings Can be Made Equal With Operations II",
        "difficulty": "Medium",
        "tags": "Hash Table, String, Sorting",
        "description": "You are given two strings s1 and s2, both of length n, consisting of lowercase English letters.\n\nYou can apply the following operation on any of the two strings any number of times:\n\nChoose any two indices i and j such that i < j and the difference j - i is even, then swap the two characters at those indices in the string.\nReturn true if you can make the strings s1 and s2 equal, and false otherwise.\n\n \n\nExample 1:\n\nInput: s1 = \"abcdba\", s2 = \"cabdab\"\nOutput: true\nExplanation: We can apply the following operations on s1:\n- Choose the indices i = 0, j = 2. The resulting string is s1 = \"cbadba\".\n- Choose the indices i = 2, j = 4. The resulting string is s1 = \"cbbdaa\".\n- Choose the indices i = 1, j = 5. The resulting string is s1 = \"cabdab\" = s2.\nExample 2:\n\nInput: s1 = \"abe\", s2 = \"bea\"\nOutput: false\nExplanation: It is not possible to make the two strings equal.\n \n\nConstraints:\n\nn == s1.length == s2.length\n1 <= n <= 105\ns1 and s2 consist only of lowercase English letters.",
        "approach": "Approach: Hash Table\nIntuition\nThis problem is an extension of 「2839. Check if Strings Can Be Made Equal With Operations I」. We can generalize the case analysis from that problem to handle this more general scenario.\n\nFrom the given exchange rules, we can observe that characters can only be swapped with other characters that have the same parity of indices. In other words, characters at even indices can only be swapped among themselves, and similarly for characters at odd indices.\n\nThis implies that the string can be divided into two independent groups based on index parity, where characters within each group can be freely rearranged. Therefore, to determine whether s1​ can be transformed into s2,we only need to check whether the character multisets match for both the even-indexed positions and the odd-indexed positions. That is, both groups must have identical character frequencies in s1 and s2.\n\nThere are multiple ways to count character frequencies and compare them. A straightforward approach is to traverse s1\n​and s2\n​\nsimultaneously in a single loop. For each index, we increment the frequency of the character from s1 and decrement the frequency of the character from s2, keeping track separately for even and odd indices.\n\nAt the end, if all frequency counts are zero, it means the character distributions match in both groups; otherwise, they do not.",
        "cpp": "class Solution {\n public:\n  bool checkStrings(string s1, string s2) {\n    vector<vector<int>> count(2, vector<int>(26));\n\n    for (int i = 0; i < s1.length(); ++i) {\n      ++count[i % 2][s1[i] - 'a'];\n      --count[i % 2][s2[i] - 'a'];\n    }\n\n    for (int i = 0; i < 26; ++i)\n      if (count[0][i] > 0 || count[1][i] > 0)\n        return false;\n\n    return true;\n  }\n};",
        "java": "class Solution {\n  public boolean checkStrings(String s1, String s2) {\n    int[][] count = new int[2][26];\n\n    for (int i = 0; i < s1.length(); ++i) {\n      ++count[i % 2][s1.charAt(i) - 'a'];\n      --count[i % 2][s2.charAt(i) - 'a'];\n    }\n\n    for (int i = 0; i < 26; ++i)\n      if (count[0][i] > 0 || count[1][i] > 0)\n        return false;\n\n    return true;\n  }\n}",
        "python": "class Solution:\n  def checkStrings(self, s1: str, s2: str) -> bool:\n    count = [collections.Counter() for _ in range(2)]\n\n    for i, (a, b) in enumerate(zip(s1, s2)):\n      count[i % 2][a] += 1\n      count[i % 2][b] -= 1\n\n    return (all(freq == 0 for freq in count[0].values()) and\n            all(freq == 0 for freq in count[1].values()))",
        "timeComplexity": "Time complexity: O(n)",
        "spaceComplexity": "Space complexity: O(k)",
        "date": "Mar 30, 2026"
    }
];